# Generated by Django 4.1.7 on 2023-03-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0002_accountemail_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='nick',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
