# Generated by Django 4.1.7 on 2023-03-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0003_account_date_alter_account_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
