# Generated by Django 4.1.7 on 2023-03-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0004_account_dislike_account_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('price', models.FloatField()),
                ('like', models.PositiveIntegerField()),
                ('dislike', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='dislike',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
