# Generated by Django 4.1.7 on 2023-03-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0005_game_alter_account_dislike_alter_account_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='games',
            field=models.ManyToManyField(to='net.game'),
        ),
    ]
