# Generated by Django 4.1.7 on 2023-03-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0006_account_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
