# Generated by Django 4.1.7 on 2023-03-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0007_alter_account_dislike_alter_account_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='changes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
